"""New type field within Skills table

Revision ID: 063e1371ab56
Revises: 69d968256ec2
Create Date: 2020-07-08 12:27:40.388709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063e1371ab56'
down_revision = '69d968256ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'type')
    # ### end Alembic commands ###
