"""language column in education and job tables

Revision ID: 5e11756a506d
Revises: 52a2b6e4234e
Create Date: 2020-07-07 19:11:57.788270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e11756a506d'
down_revision = '52a2b6e4234e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('language', sa.String(length=2), nullable=True))
    op.add_column('job', sa.Column('language', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'language')
    op.drop_column('education', 'language')
    # ### end Alembic commands ###
