"""Certification table

Revision ID: 6b96c36a12f1
Revises: eadf07cb550b
Create Date: 2020-07-08 17:25:43.499540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b96c36a12f1'
down_revision = 'eadf07cb550b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certification')
    # ### end Alembic commands ###
