"""Settings table

Revision ID: b5b746be0482
Revises: 456544d9fcb6
Create Date: 2020-07-06 15:26:44.270466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b746be0482'
down_revision = '456544d9fcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('param_name', sa.String(length=100), nullable=True),
    sa.Column('param_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_param_name'), 'settings', ['param_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_param_name'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
