"""EN fields for Skills table

Revision ID: eadf07cb550b
Revises: 063e1371ab56
Create Date: 2020-07-08 13:40:27.366465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eadf07cb550b'
down_revision = '063e1371ab56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('description_en', sa.String(length=100), nullable=True))
    op.add_column('skills', sa.Column('name_en', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'name_en')
    op.drop_column('skills', 'description_en')
    # ### end Alembic commands ###
